import 'package:flutter/material.dart';

class ColorUtil {
  static const white = Colors.white;
  static const lightPurple = Color(0xff8A8CBD);
  static const navyBlue = Color(0xff007AB9);
  static const assignmentText = Color(0xff525bff);
  static const assignmentBg = Color(0x190cb1ff);
  static const circularBg = Color(0xffffa781);
  static const circularText = Color(0xff5b0e2d);
  static const examText = Color(0xff05b79c);
  static const examBg = Color(0x1961e3a5);
  static const reportText = Color(0xfffd4585);
  static const reportBg = Color(0x19fe998c);
  static const dateColor = Color(0xff252525);
  static const blue = Color(0xff35378c);
  static const mainBg = Color(0xffe5e4f2);
  static const borderSep = Color(0xff3f526d);
  static const attachmentColor = Color(0xff25dbdc);
  static const shareColor = Color(0xff6891fc);
  static const green = Color(0xff26de81);
  static const greybg = Colors.grey;
  static const circularRed = Color(0xfffc5c65);
  static const shimmerBaseColor = Color(0xffcda4de);
  static const shimmerHglt = Color(0xffc3d0be);
  static const eventIndiColor = Color(0xfffed330);
  static const indicatorBlack = Color(0xff343434);
  static const examIndiColor = Color(0xff5fd2d0);
  static const absentIndiColor = Color(0xfffc5c65);
  static const totalDaysIndicator = Color(0xff6e6e6e);
  static const tabIndicator = Color(0xff34378b);
  static const tabUnselected = Color(0xFF414D55);
  static const eventYellow = Color(0xfff7d794);
  static const eventDate = Color(0xffd39a23);
  static const calendarFont = Color(0xff5c5c5c);
  static const bg = Color(0xffececf9);
  static const feegreen = Color(0xff24c272);
  static const feegrlt = Color(0x1924c272);
  static const feeblue = Color(0xff2884d5);
  static const feebluelt = Color(0x192884d5);
  static const feetitle = Color(0xff5558ff);
  static const paidBor = Color(0xff19a2a0);
  static const profName = Color(0xff517bfa);
  static const studName = Color(0xff8829e1);
  static const subBlue =  Color(0xff778beb);
  static const subGold = Color(0xfff19065);
  static const downloadClr = Color(0xff787878);
}